-- schema.sql
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CLIENTE(
   ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   NOMBRE VARCHAR (250) NOT NULL,
   APELLIDO VARCHAR (250) NOT NULL,
   EMAIL VARCHAR (250) NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);