DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes(
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   nombre VARCHAR (250) NOT NULL,
   apellido VARCHAR (250) NOT NULL,
   email VARCHAR (250) NOT NULL UNIQUE,
   created_at TIMESTAMP NOT NULL
);
